# Server Port
server.port=8082

# Application Name
spring.application.name=user-service

# H2 Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/userdb?TimeZone=Asia/Kolkata
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.database=postgresql 

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true